# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_generated', models.BooleanField(default=False)),
                ('rating', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_generated', models.BooleanField(default=False)),
                ('rating', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Child', 'Child of'), ('Related', 'Related to'), ('Subset of', 'Subset of'), ('Superset of', 'Superset of'), ('Synonym for', 'Synonym for')], max_length=12)),
                ('rating', models.FloatField(default=1.0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='user_generated',
        ),
        migrations.RemoveField(
            model_name='document',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='communities',
        ),
        migrations.AddField(
            model_name='community',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='community',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Bilingual', 'Bilingual')], default='EN', max_length=8),
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_tags', related_query_name='from_tag', to='classifier.Tag'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_tags', related_query_name='to_tag', to='classifier.Tag'),
        ),
        migrations.AddField(
            model_name='rating',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Community'),
        ),
        migrations.AddField(
            model_name='rating',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Document'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Community'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Tag'),
        ),
    ]
