# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_auto_20170528_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(default='Forever forever forever', verbose_name=16000),
            preserve_default=False,
        ),
    ]
