# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_auto_20170528_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(max_length=16000),
        ),
    ]
