# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20170528_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French')], default='EN', max_length=4),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('Subject category', 'Subject category'), ('History note', 'History note'), ('Related term', 'Related term'), ('Broader term', 'Broader term'), ('Narrower term', 'Narrower term'), ('Used for', 'Used for'), ('Use', 'Use'), ('Translation', 'Translation')], max_length=12),
        ),
    ]
