# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_auto_20170529_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='community',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='atip_community',
            field=models.FloatField(default=0.0, verbose_name='Access to Information'),
        ),
        migrations.AddField(
            model_name='rating',
            name='auditor_community',
            field=models.FloatField(default=0.0, verbose_name='Internal Auditors'),
        ),
        migrations.AddField(
            model_name='rating',
            name='communication_community',
            field=models.FloatField(default=0.0, verbose_name='Communications'),
        ),
        migrations.AddField(
            model_name='rating',
            name='evaluator_community',
            field=models.FloatField(default=0.0, verbose_name='Evaluators'),
        ),
        migrations.AddField(
            model_name='rating',
            name='financial_community',
            field=models.FloatField(default=0.0, verbose_name='Financial Officers'),
        ),
        migrations.AddField(
            model_name='rating',
            name='hr_community',
            field=models.FloatField(default=0.0, verbose_name='Human Resources'),
        ),
        migrations.AddField(
            model_name='rating',
            name='im_community',
            field=models.FloatField(default=0.0, verbose_name='Information Management'),
        ),
        migrations.AddField(
            model_name='rating',
            name='it_community',
            field=models.FloatField(default=0.0, verbose_name='Information Technology'),
        ),
        migrations.AddField(
            model_name='rating',
            name='materiel_community',
            field=models.FloatField(default=0.0, verbose_name='Materiel Management'),
        ),
        migrations.AddField(
            model_name='rating',
            name='policy_community',
            field=models.FloatField(default=0.0, verbose_name='Policy'),
        ),
        migrations.AddField(
            model_name='rating',
            name='procurement_community',
            field=models.FloatField(default=0.0, verbose_name='Purchasing Specialists'),
        ),
        migrations.AddField(
            model_name='rating',
            name='real_property_community',
            field=models.FloatField(default=0.0, verbose_name='Real Property'),
        ),
        migrations.AddField(
            model_name='rating',
            name='regulator_community',
            field=models.FloatField(default=0.0, verbose_name='Regulators'),
        ),
        migrations.AddField(
            model_name='rating',
            name='science_community',
            field=models.FloatField(default=0.0, verbose_name='Science & Tech'),
        ),
        migrations.AddField(
            model_name='rating',
            name='security_community',
            field=models.FloatField(default=0.0, verbose_name='Security Specialists'),
        ),
        migrations.AddField(
            model_name='rating',
            name='service_community',
            field=models.FloatField(default=0.0, verbose_name='Services'),
        ),
    ]
