# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0007_rating_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.CharField(default='gctools', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('Subject category', 'Subject category'), ('History note', 'History note'), ('Related term', 'Related term'), ('Broader term', 'Broader term'), ('Narrower term', 'Narrower term'), ('Used for', 'Used for'), ('Use', 'Use'), ('Translation', 'Translation')], default='Related term', max_length=16),
        ),
    ]
