# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0008_auto_20170601_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='keywords',
            new_name='rake_keywords',
        ),
        migrations.AddField(
            model_name='document',
            name='user_keywords',
            field=models.CharField(default='gctools', max_length=128),
            preserve_default=False,
        ),
    ]
