# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0010_auto_20170602_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
